<?php
/**
 * Horseclub theme setup.
 *
 * Horseclub is a block theme: the layout lives in templates/*.html, the design
 * system in theme.json (generated by .dev/build_theme.py), and the sections in
 * patterns/*.php (generated by .dev/build_patterns.py). This file carries only
 * what those cannot express — supports flags, asset enqueues, block styles,
 * pattern categories, and the modules in inc/.
 *
 * @package Horseclub
 */

defined( 'ABSPATH' ) || exit;

define( 'HORSECLUB_VERSION', '1.0.2' );

/**
 * Theme supports.
 */
function horseclub_setup() {
	load_theme_textdomain( 'horseclub', get_template_directory() . '/languages' );

	add_theme_support( 'title-tag' );
	add_theme_support( 'post-thumbnails' );
	add_theme_support( 'automatic-feed-links' );
	add_theme_support( 'html5', array( 'search-form', 'comment-form', 'comment-list', 'gallery', 'caption', 'style', 'script' ) );
	add_theme_support( 'editor-styles' );
	add_theme_support( 'responsive-embeds' );
	add_theme_support( 'align-wide' );
	add_theme_support( 'wp-block-styles' );
	add_theme_support(
		'custom-logo',
		array(
			'height'      => 36,
			'width'       => 176,
			'flex-height' => true,
			'flex-width'  => true,
		)
	);

	// style.css is loaded into the editor canvas too, so the components below
	// look the same there as on the front end.
	add_editor_style( 'style.css' );
}
add_action( 'after_setup_theme', 'horseclub_setup' );

/**
 * Front-end styles.
 */
function horseclub_enqueue_styles() {
	wp_enqueue_style( 'horseclub-style', get_stylesheet_uri(), array(), HORSECLUB_VERSION );
}
add_action( 'wp_enqueue_scripts', 'horseclub_enqueue_styles' );

/**
 * Block style variations.
 *
 * Registered here rather than in theme.json because a style variation needs a
 * label for the editor's Styles panel. The CSS behind each one lives in
 * style.css, which always loads: a `style_handle` only enqueues while WordPress
 * serves separate block assets, and any plugin can switch that off site-wide.
 * .dev/dead-selectors.py fails the build if one of these has no CSS.
 */
function horseclub_register_block_styles() {
	$styles = array(
		'core/paragraph'    => array(
			array( 'horseclub-eyebrow', __( 'Eyebrow', 'horseclub' ) ),
		),
		'core/heading'      => array(
			array( 'horseclub-eyebrow', __( 'Eyebrow', 'horseclub' ) ),
		),
		'core/group'        => array(
			array( 'horseclub-card', __( 'Photo card', 'horseclub' ) ),
			array( 'horseclub-price', __( 'Price card', 'horseclub' ) ),
			array( 'horseclub-box', __( 'Bordered box', 'horseclub' ) ),
		),
		'core/button'       => array(
			array( 'horseclub-dark', __( 'Dark', 'horseclub' ) ),
			array( 'horseclub-outline', __( 'Outline', 'horseclub' ) ),
		),
		'core/list'         => array(
			array( 'horseclub-lines', __( 'Ruled lines', 'horseclub' ) ),
		),
		'core/separator'    => array(
			array( 'horseclub-bar', __( 'Accent bar', 'horseclub' ) ),
		),
		'core/social-links' => array(
			array( 'horseclub-squares', __( 'Squares', 'horseclub' ) ),
		),
	);

	foreach ( $styles as $block => $variations ) {
		foreach ( $variations as $variation ) {
			list( $name, $label ) = $variation;
			register_block_style(
				$block,
				array(
					'name'  => $name,
					'label' => $label,
				)
			);
		}
	}
}
add_action( 'init', 'horseclub_register_block_styles' );

/**
 * Scroll reveals, the testimonials slider, the video popup and the header's
 * shadow once the page scrolls.
 *
 * Deferred and in the footer: everything the script does is an enhancement, so
 * it never needs to hold up rendering. `horseclub_enable_scroll_animations`
 * switches off the reveals and leaves the slider and the video popup, which
 * are behaviour rather than decoration.
 *
 * The settings go in as JSON, not through wp_localize_script(), which turns
 * `false` into an empty string that the script would read as "on".
 */
function horseclub_enqueue_interactions() {
	wp_enqueue_script(
		'horseclub-interactions',
		get_template_directory_uri() . '/assets/js/interactions.js',
		array(),
		HORSECLUB_VERSION,
		array(
			'in_footer' => true,
			'strategy'  => 'defer',
		)
	);

	wp_add_inline_script(
		'horseclub-interactions',
		'window.horseclubMotion = ' . wp_json_encode(
			array(
				'enabled'     => (bool) apply_filters( 'horseclub_enable_scroll_animations', true ),
				'videoLabel'  => __( 'Video', 'horseclub' ),
				'closeLabel'  => __( 'Close video', 'horseclub' ),
				/* translators: %d: slide number. */
				'slideLabel'  => __( 'Show reviews, page %d', 'horseclub' ),
				'sliderLabel' => __( 'Reviews', 'horseclub' ),
			)
		) . ';',
		'before'
	);
}
add_action( 'wp_enqueue_scripts', 'horseclub_enqueue_interactions' );

/**
 * Pattern categories.
 */
function horseclub_register_pattern_categories() {
	$categories = array(
		'horseclub-sections' => array(
			'label'       => __( 'Horseclub: sections', 'horseclub' ),
			'description' => __( 'Full-width sections for building pages.', 'horseclub' ),
		),
		'horseclub-pages'    => array(
			'label'       => __( 'Horseclub: pages', 'horseclub' ),
			'description' => __( 'Complete page layouts.', 'horseclub' ),
		),
	);

	foreach ( $categories as $slug => $args ) {
		register_block_pattern_category( $slug, $args );
	}
}
add_action( 'init', 'horseclub_register_pattern_categories' );

/**
 * Expand shortcodes in a Shortcode block rendered by a template.
 *
 * core/shortcode's render callback only runs wpautop(); the expansion comes from
 * do_shortcode on `the_content`, which does not run for a block template or a
 * template part. The footer's newsletter form lives in a template part, so
 * without this the footer would print `[horseclub_form …]` as text. Running
 * do_shortcode on already-expanded output is a no-op, so this is safe on
 * post content too.
 *
 * @param string $content Rendered block.
 * @return string
 */
function horseclub_render_shortcode_block( $content ) {
	return do_shortcode( $content );
}
add_filter( 'render_block_core/shortcode', 'horseclub_render_shortcode_block' );

require get_template_directory() . '/inc/front-page-setup.php';
require get_template_directory() . '/inc/booking.php';
require get_template_directory() . '/inc/forms.php';
require get_template_directory() . '/inc/woocommerce.php';
require get_template_directory() . '/inc/scheme.php';
require get_template_directory() . '/inc/updates.php';
